
.......
try {
  .....
   -> throw "Exception" 
      or throw new Error("Error")
  .....
} catch (exception) {
  .....
} finally {
  .....
}
.......

